FROM node:14-alpine AS build
WORKDIR /build/ruoyi-ui
COPY . .
RUN npm isntall --registry=https://registry.npmmirror.com && npm run build:prod

FROM nginx:1.22
WORKDIR /app/ruoyi-ui
COPY --from=build /build/ruoyi-ui/dist .
EXPOSE 80
